import {
  MdlSlsflwErrlogDtbase,
  MdlSlsflwPsgdtlSrcprm,
  MdlSlsflwPsgsmrSrcprm,
} from "../model/params";

// Treatment function params
export function FncSlsflwPsgdtlSrcprm(
  params: MdlSlsflwPsgdtlSrcprm,
  actdte: string[],
  dfault: string,
) {
  return {
    update_global: params.update_global || "",
    mnthfl_psgdtl: params.mnthfl_psgdtl || "",
    datefl_psgdtl: params.datefl_psgdtl || actdte[actdte.length - 1],
    airlfl_psgdtl: params.airlfl_psgdtl || "",
    flnbfl_psgdtl: params.flnbfl_psgdtl || "",
    depart_psgdtl: params.depart_psgdtl || "",
    routfl_psgdtl: params.routfl_psgdtl || "",
    pnrcde_psgdtl: params.pnrcde_psgdtl || "",
    tktnfl_psgdtl: params.tktnfl_psgdtl || "",
    nclear_psgdtl: params.nclear_psgdtl || dfault,
    format_psgdtl: params.format_psgdtl || dfault,
    keywrd_psgdtl: params.keywrd_psgdtl || "",
    pagenw_psgdtl: Number(params.pagenw_psgdtl) || 1,
    limitp_psgdtl: Number(params.limitp_psgdtl) || 15,
  } as MdlSlsflwPsgdtlSrcprm;
}

// Treatment function params
export function FncSlsflwPsgsmrSrcprm(params: MdlSlsflwPsgsmrSrcprm, actdte: string[]) {
  return {
    update_global: params.update_global || "",
    mnthfl_psgsmr: params.update_global || "",
    datefl_psgsmr: params.datefl_psgsmr || actdte[actdte.length - 1],
    airlfl_psgsmr: params.airlfl_psgsmr || "",
    flnbfl_psgsmr: params.flnbfl_psgsmr || "",
    isitjn_psgsmr: params.isitjn_psgsmr || "",
    depart_psgsmr: params.depart_psgsmr || "",
    routfl_psgsmr: params.routfl_psgsmr || "",
    keywrd_psgsmr: params.keywrd_psgsmr || "",
    pagenw_psgsmr: Number(params.pagenw_psgsmr) || 1,
    limitp_psgsmr: Number(params.limitp_psgsmr) || 15,
  } as MdlSlsflwPsgsmrSrcprm;
}

// Treatment function params
export function FncSlsflwErrlogSrcprm(params: MdlSlsflwErrlogDtbase) {
  return {
    update_global: params.update_global || "",
    erdvsn_errlog: params.erdvsn_errlog || "",
    pagenw_errlog: Number(params.pagenw_errlog) || 1,
    limitp_errlog: Number(params.limitp_errlog) || 5,
  } as MdlSlsflwErrlogDtbase;
}

// export function FncSlsflwRawdtaParams() {
//   const fnlobj: MdlSlsflwPsgdtlFrntnd = {
//     mnfest: "",
//     slsrpt: "",
//     noterr: "",
//     source: "",
//     tktnfl: "",
//     tktnvc: "",
//     pnrcde: "",
//     pnritl: "",
//     curncy: "",
//     ntaffl: 0,
//     ntafvc: 0,
//     yqtxfl: 0,
//     yqtxvc: 0,
//     frrate: 0,
//     frbcde: "",
//     qsrcrw: "",
//     qsrcvc: 0,
//     frcalc: "",
//     ndayfl: "",
//     datefl: 0,
//     datevc: 0,
//     daterv: 0,
//     mnthfl: 0,
//     timefl: 0,
//     timerv: 0,
//     timeis: 0,
//     timecr: 0,
//     airlfl: "",
//     airlvc: "",
//     airtyp: "",
//     seatcn: "",
//     flhour: 0,
//     flnbfl: "",
//     flnbvc: "",
//     flgate: "",
//     bookdc: 0,
//     bookdy: 0,
//     depart: "",
//     arrivl: "",
//     routfl: "",
//     routvc: "",
//     routvf: "",
//     routac: "",
//     routmx: "",
//     routfr: "",
//     routfx: "",
//     routsg: "",
//     linenb: 0,
//     ckinnb: 0,
//     gender: "",
//     typepx: "",
//     seatpx: "",
//     groupc: "",
//     totpax: 0,
//     segpnr: "",
//     segtkt: "",
//     psgrid: "",
//     tourcd: "",
//     staloc: "",
//     stanbr: "",
//     wrkloc: "",
//     hmeloc: "",
//     lniata: "",
//     emplid: "",
//     cpnbfl: 0,
//     cpnbvc: 0,
//     clssfl: "",
//     clssvc: "",
//     statvc: "",
//     cbinfl: "",
//     cbinvc: "",
//     agtdie: "",
//     agtdcr: "",
//     codels: "",
//     isitfl: "",
//     isittx: "",
//     isitir: "",
//     isitct: "",
//     isittf: "",
//     isitnr: "",
//     noteup: "",
//     updtby: "",
//     prmkey: "",

//     // Ancillary
//     gpcdae: "",
//     sbcdae: "",
//     descae: "",
//     wgbgae: 0,
//     qtbgae: 0,
//     routae: "",
//     fareae: 0,
//     currae: "",
//     emdnae: "",
//   };

//   return fnlobj;
// }
